import math
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException

from api.schemas import (
    ApplicantRequest,
    ExplanationFactor,
    HealthResponse,
    ModelInfoResponse,
    RiskResponse,
)

from core.risk import (
    build_risk_description,
    classify_risk,
    get_risk_band_information,
)

from loan_risk_model import (
    build_explanation,
    explain_prediction,
    load_models,
    predict_risk,
)


# ============================================================
# PROJECT PATH
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Loan Risk Assessment API",
    description=(
        "Inference API for estimating modeled loan non-payment "
        "risk using a calibrated Logistic Regression model."
    ),
    version="1.0.0",
)


# ============================================================
# LOAD MODELS
# ============================================================

try:

    final_model, explanation_model = load_models()

    MODEL_LOADED = True
    MODEL_LOAD_ERROR = None

except Exception as exc:

    final_model = None
    explanation_model = None

    MODEL_LOADED = False
    MODEL_LOAD_ERROR = str(exc)


# ============================================================
# MODEL METADATA
# ============================================================

TARGET_NAME = "not.fully.paid"


# ============================================================
# BUILD MODEL INPUT
# ============================================================

def build_model_input(
    applicant: ApplicantRequest,
) -> pd.DataFrame:
    """
    Convert user-friendly API values into the exact feature
    representation expected by the trained ML pipeline.
    """

    # --------------------------------------------------------
    # Interest rate
    #
    # API:
    #     15.51
    #
    # Model:
    #     0.1551
    # --------------------------------------------------------

    interest_rate_model = (
        applicant.interest_rate / 100.0
    )

    # --------------------------------------------------------
    # Annual income
    #
    # API:
    #     actual annual income
    #
    # Model:
    #     log.annual.inc
    #
    # The training dataset uses the logarithm of annual income.
    # --------------------------------------------------------

    log_annual_income = math.log(
        applicant.annual_income
    )

    # --------------------------------------------------------
    # Credit history
    #
    # API:
    #     years
    #
    # Model:
    #     days.with.cr.line
    # --------------------------------------------------------

    days_with_credit_line = (
        applicant.credit_history_years * 365.25
    )

    # --------------------------------------------------------
    # Construct model dataframe
    #
    # IMPORTANT:
    # These names must match the training features exactly.
    # --------------------------------------------------------

    model_input = pd.DataFrame(
        [
            {
                "purpose": applicant.purpose,
                "int.rate": interest_rate_model,
                "installment": applicant.installment,
                "log.annual.inc": log_annual_income,
                "dti": applicant.dti,
                "fico": applicant.fico,
                "days.with.cr.line": days_with_credit_line,
                "revol.bal": applicant.revolving_balance,
                "revol.util": applicant.credit_utilization,
                "inq.last.6mths": applicant.recent_inquiries,
                "delinq.2yrs": applicant.delinquencies,
                "pub.rec": applicant.public_records,
            }
        ]
    )

    return model_input


# ============================================================
# CONVERT EXPLANATIONS TO API FORMAT
# ============================================================

def build_api_explanations(
    explanation_df: pd.DataFrame,
    applicant: pd.DataFrame,
) -> tuple[
    list[ExplanationFactor],
    list[ExplanationFactor],
]:
    """
    Convert the explanation dataframe generated by the
    existing ML explanation logic into API response objects.
    """

    explanations = build_explanation(
        explanation_df,
        applicant,
        top_n=5,
    )

    risk_increasing = []

    risk_reducing = []

    for _, row in explanations.iterrows():

        factor = ExplanationFactor(
            display_name=str(
                row["display_name"]
            ),
            direction=str(
                row["direction"]
            ),
            text=str(
                row["text"]
            ),
        )

        if row["direction"] == "Risk-increasing":

            risk_increasing.append(factor)

        elif row["direction"] == "Risk-reducing":

            risk_reducing.append(factor)

    return (
        risk_increasing,
        risk_reducing,
    )


# ============================================================
# HEALTH ENDPOINT
# ============================================================

@app.get(
    "/health",
    response_model=HealthResponse,
)
def health_check():

    return HealthResponse(
        status=(
            "healthy"
            if MODEL_LOADED
            else "model_load_failed"
        ),
        model_loaded=MODEL_LOADED,
    )


# ============================================================
# MODEL INFORMATION ENDPOINT
# ============================================================

@app.get(
    "/model-info",
    response_model=ModelInfoResponse,
)
def model_info():

    return ModelInfoResponse(
        model_type="Calibrated Logistic Regression",
        target=TARGET_NAME,
        risk_bands=get_risk_band_information(),
        note=(
            "Risk thresholds are prototype segmentation "
            "thresholds derived from this project's calibrated "
            "validation analysis. They are not bank policy or "
            "loan approval rules."
        ),
    )


# ============================================================
# PREDICTION ENDPOINT
# ============================================================

@app.post(
    "/predict",
    response_model=RiskResponse,
)
def predict(
    applicant: ApplicantRequest,
):

    # --------------------------------------------------------
    # Ensure model is available
    # --------------------------------------------------------

    if not MODEL_LOADED:

        raise HTTPException(
            status_code=503,
            detail=(
                "Model is not available. "
                f"Model loading error: {MODEL_LOAD_ERROR}"
            ),
        )

    try:

        # ----------------------------------------------------
        # Convert human-friendly input to model input
        # ----------------------------------------------------

        model_input = build_model_input(
            applicant
        )

        # ----------------------------------------------------
        # Model prediction
        # ----------------------------------------------------

        prediction = predict_risk(
            model_input,
            final_model,
        )

        probability = float(
            prediction["probability"]
        )

        # ----------------------------------------------------
        # Centralized risk classification
        # ----------------------------------------------------

        risk_category = classify_risk(
            probability
        )

        # ----------------------------------------------------
        # Risk description
        # ----------------------------------------------------

        description = build_risk_description(
            risk_category,
            probability,
        )

        # ----------------------------------------------------
        # Individual explanation
        # ----------------------------------------------------

        explanation_df = explain_prediction(
            model_input,
            explanation_model,
        )

        (
            risk_increasing,
            risk_reducing,
        ) = build_api_explanations(
            explanation_df,
            model_input,
        )

        # ----------------------------------------------------
        # Final API response
        # ----------------------------------------------------

        return RiskResponse(
            probability=round(
                probability,
                6,
            ),
            probability_percent=round(
                probability * 100,
                2,
            ),
            risk_category=risk_category,
            description=description,
            risk_increasing_factors=risk_increasing,
            risk_reducing_factors=risk_reducing,
            disclaimer=(
                "This is a machine-learning risk estimate. "
                "It is not a standalone loan approval or "
                "rejection decision."
            ),
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                f"Prediction failed: {str(exc)}"
            ),
        )